### ISSUE TITLE
Draw event example not working

### ISSUE THREAD

**Issue by ralphstodomingo** [allenhwkim/react-openlayers#17]
When trying to supply `source` to `<layer.Vector>` I get the error "Assertion failed. See https://openlayers.org/en/v4.0.1/doc/errors/#44 for details." You can initialize layer.Vector without source, but this means you cannot use the same source for interaction.Draw.

**Comment by ralphstodomingo** [comment]
I was on openlayers@4.1.0. Downgrading to 4.0.1 solved it.

**Comment by edelater** [comment]
Aaaaah. Thanks!! I've been struggling with the same problem for the past 8 hours...

**Comment by ralphstodomingo** [comment]
If I didn't have the desperate option of using DevTools on the examples page, I wouldn't have figured it out either. :D
