### ISSUE TITLE
Dynamic interaction.Draw type

### ISSUE THREAD

**Issue by ralphstodomingo** [allenhwkim/react-openlayers#18]
I'm trying to make the type option of `interaction.Draw` dynamic. My component rerenders, but the type of the interaction does not change.

**Comment by ralphstodomingo** [comment]
I've found out that the `interaction.Draw` component does not have a `componentWillReceiveProps()` function.

**Comment by ralphstodomingo** [comment]
And they'll likely need a `componentWillUnmount()` as well when they are to be removed.

**Comment by allenhwkim** [comment]
I am not very good at React although I made this module,

Never used this.

https://facebook.github.io/react/docs/react-component.html#componentwillreceiveprops
`componentWillReceiveProps() is invoked before a mounted component receives new props. `

Please make a pull request if it is right one.

**Comment by ralphstodomingo** [comment]
That function should update the component if it received new props.

Will try.
