### ISSUE TITLE
Vector tiles

### ISSUE THREAD

**Issue by Mashi** [allenhwkim/react-openlayers#2]
Thank you so much for this!

Sorry for being so ignorant: This is probably not the right forum for making feature request, but the final piece of the jigsaw which would make this package perfect in my opinion is inclusion of a vector tile example layer.

**Comment by allenhwkim** [comment]
https://rawgit.com/allenhwkim/react-openlayers/master/app/index.html#/layers/vector

**Comment by Mashi** [comment]
https://openmaptiles.org/docs/website/openlayers/

**Comment by allenhwkim** [comment]
Do you want the example comPlate?

**Comment by Mashi** [comment]
A complete working example of vector tiles would make an awesome addition.  Vector tiles are really becoming incredibly popular these days and so far nobody else has been able to show how to integrate vector tiles in a React app.  Thanks for the amazing work you have done.

**Comment by allenhwkim** [comment]
Here I added the VectorTile example which is presented from openlayers.org
http://openlayers.org/en/latest/examples/mapbox-vector-tiles.html

https://rawgit.com/allenhwkim/react-openlayers/master/app/index.html#/layers/vector-tile

I tried to use this, but it did not quite follow OpenLayer conventions, IMO
https://openmaptiles.org/docs/website/openlayers/

You may play around little bit and LMK if I need to improve any.

**Comment by allenhwkim** [comment]
VectorTile has been implemented.
