### ISSUE TITLE
Any plans to support OpenLayers 4?

### ISSUE THREAD

**Issue by darrencruse** [allenhwkim/react-openlayers#27]
Was looking to use react-openlayers but my coworkers (who have much more OpenLayers experience than I) were encouraging me to use OL4...

(they said OL4 had some features to better limit the resulting webpack javascript bundle size?)

**Comment by allenhwkim** [comment]
It's already OL4
https://github.com/allenhwkim/react-openlayers/blob/master/package.json#L47

**Comment by darrencruse** [comment]
Oh awesome!!

(just fyi/fwiw I'm new to OpenLayers so maybe I read it differently than others would have but it was the description "A minimal React wrapper of OpenLayer 3+ written in TypeScript" that I misread as "OpenLayers 3" I didn't even notice the "+" part until your message)
