### ISSUE TITLE
Other interactions?

### ISSUE THREAD

**Issue by ralphstodomingo** [allenhwkim/react-openlayers#3]
Thank you for this.

Looking at the source code, there isn't any other interactions aside from the default and Select, Draw and Modify. Is this project in active development?

**Comment by allenhwkim** [comment]
Yes active project it is

**Comment by allenhwkim** [comment]
Could you please list missing interactions?

**Comment by prime-ralph** [comment]
The Openlayer documentation has a list of interactions: 
http://openlayers.org/en/latest/apidoc/ol.interaction.html
and based on this:
https://github.com/allenhwkim/react-openlayers/blob/master/src/interactions/index.tsx
Only three of them have been implemented. Found this out when I tried to do Snap and Translate.

I also had an error 'Cannot access property D of undefined' or something even while doing the basic tiling example.
I've had experience using ngMaps as well before, so I thank you for the work you've been doing.

**Comment by allenhwkim** [comment]
Added all interactions, and released as 0.2.0

**Comment by allenhwkim** [comment]
I also had this error `Cannot access property D of undefined` when I run it with SystemJS.

**Comment by prime-ralph** [comment]
If I find the time I'll try to contribute. It would be a good idea to replicate the examples page of openlayers to ensure we have 100% coverage of the api.
Thanks for your attention!

**Comment by allenhwkim** [comment]
@prime-ralph thanks. I will try to cover all API(at least I thought I covered it all), but the examples are very hard to build.
