### ISSUE TITLE
Missing .d.ts

### ISSUE THREAD

**Issue by AAllport** [allenhwkim/react-openlayers#30]
I am aware that I am probably doing something incorrectly, however, when compiling typescript, I am getting the error ``Could not find a declaration file for module 'react-openlayers'``

Steps Taken:
```npm install --save react-openlayers```
```ts
import {
  interaction, layer, custom, control, //name spaces
  Interactions, Overlays, Controls,     //group
  Map, Layers, Overlay, Util    //objects
} from "react-openlayers";
```
```webpack```

ms code underlines ``react-openlayers`` as an error, as it cannot find the d.ts
If anyone could advise on how to proceed, I would be most appriciative

**Comment by apearson** [comment]
What was the solution to this?
