### ISSUE TITLE
How i can resize width and height of map?

### ISSUE THREAD

**Issue by samrandhawa4** [allenhwkim/react-openlayers#4]
Want to resize map, height =100% , how i can do that?

**Comment by allenhwkim** [comment]
please override ol.css.
https://openlayers.org/en/latest/doc/quickstart.html

**Comment by samrandhawa4** [comment]
I tried your suggested code but still its not working. Please help me out.  i cant see any relevant example in your code about draw events 
```js <interaction.Draw source={ source } type="Polygon" onDrawend={ alert('hi') } />
