### ISSUE TITLE
[QUESTION] How to set map size?

### ISSUE THREAD

**Issue by andre-engelbrecht** [allenhwkim/react-openlayers#41]
Hi @allenhwkim , how can I set the size of the map?

It seems to default to { width: "100%", height: "300px" }, with no apparent way to override/set a custom width/height?

Best regards,
André

**Comment by Niondir** [comment]
I have the same issue.
Since I see not much activity in this project, I forked the project to apply my own fixes. Feel free to help me improve the wrapper: https://github.com/Lobaro/react-openlayers

Fixing sizing issues will be next.

**Comment by Niondir** [comment]
I added a property "rootStyle" for the Map component to solve this issue: https://github.com/lobaro/react-openlayers/commit/369189bd0e18a7ee79fed2e9ebf17aa28f73ec4c

**Comment by andre-engelbrecht** [comment]
I've found a different mapping component that I'm going to use, thanks.

André Engelbrecht
ajc.mfl@gmail.com

------ Original Message ------

**Comment by Niondir** [comment]
Which one do you use now?

**Comment by andre-engelbrecht** [comment]
https://react-leaflet.js.org/
