### ISSUE TITLE
Centre is not woking on map component

### ISSUE THREAD

**Issue by samrandhawa4** [allenhwkim/react-openlayers#6]
I tried to use centre option of map componenet but its not placing me on new Zealand. Can you please check that if you change centre in your code it worked or not. even i don't like the map default colours , they are dull , how i can change colour of sear and countries just like google maps. Thank you for your support Allen.
```js 
  <Map view={ { center: [-36.848461, 174.763336] } }>

**Comment by allenhwkim** [comment]
You are trying google maps way lat/lng, 
try standard `long/lat`  `[174.763336, -36.848461]`
It may not work, then as you see here, we need to make proper coordinate, http://openlayers.org/en/latest/apidoc/ol.View.html
e.g., 
```
ol.proj.transform([long, lat], 'EPSG:4326', 'EPSG:3857')
```
Ref: http://gis.stackexchange.com/questions/112892/change-openlayers-3-view-center
