### ISSUE TITLE
Marker style not working 

### ISSUE THREAD

**Issue by samrandhawa4** [allenhwkim/react-openlayers#7]
I tried to implemet your this example https://rawgit.com/allenhwkim/react-openlayers/master/app/index.html#/interactions/modify. But i got following error. please update it. Thanks
```js
pa {message: "Assertion failed. See https://openlayers.org/en/v4.0.1/doc/errors/#41 for details.", code: 41, name: "AssertionError"}

**Comment by allenhwkim** [comment]
I don't have that error. what do you want me to update?

**Comment by ralphstodomingo** [comment]
This is probably because you were in a wrong version.
